name: ${project.name}
description: ${project.description}
main: org.eleanorsilly.mc.notes.NotePlugin
version: ${project.version}
authors:
  - eleanorsilly

commands:
  note:
    description: Add, remove or see notes or warnings. /note help for more details.
    usage: /note [subcommand] [player] [additional arguments]
    aliases: [notes, warn, warns, warning, warnings]

permissions:
  simplenotes.*:
    description: Gives access to all commands of the plugin. Should be used sparingly, e.g. for admins.
    children:
      simplenotes.addnotes: true
      simplenotes.removenotes: true
      simplenotes.see.self.notes: true
      simplenotes.see.self.warns: true
      simplenotes.see.others.notes: true
      simplenotes.see.others.warns: true
  simplenotes.addnotes:
    description: Gives the permission to add notes/warnings.
  simplenotes.removenotes:
    description: Gives the permission to remove notes/warnings.
  simplenotes.see.*:
    description: Gives the permission to see the notes/warnings of all players.
    children:
      simplenotes.see.self.notes: true
      simplenotes.see.self.warns: true
      simplenotes.see.others.notes: true
      simplenotes.see.others.warns: true
  simplenotes.see.self.*:
    description: Gives the permission to see your own notes/warnings
    children:
      simplenotes.see.self.notes: true
      simplenotes.see.self.warns: true
  simplenotes.see.self.notes:
    description: Gives the permission to see your own notes
  simplenotes.see.self.warns:
    description: Gives the permission to see your own warnings
  simplenotes.see.others.*:
    description: "Gives the permission to see other people's notes/warnings"
    children:
      simplenotes.see.others.notes: true
      simplenotes.see.others.warns: true
  simplenotes.see.others.notes:
    description: "Gives the permission to see other people's notes"
  simplenotes.see.others.warns:
    description: "Gives the permission to see other people's warnings"
