name: ${project.name}
description: ${project.description}
main: org.eleanorsilly.mc.notes
version: ${project.version}
authors:
  - eleanorsilly
softdepend:
  - Essentials

commands:
  notecommand:
    description: The main command of the plugin. /note help for more details.
    usage: /note [args]
    aliases: [notes, warning, warnings]

permissions:
  simplenotes.*:
    description: Gives access to all commands of the plugin. Should be used sparingly, e.g. for admins.
    children:
      simplenotes.addnotes: true
      simplenotes.removenotes: true
      simplenotes.seenotes.self: true
      simplenotes.seenotes.others: true
  simplenotes.addnotes:
    description: Gives the permission to add notes/warnings.
  simplenotes.removenotes:
    description: Gives the permission to remove notes/warnings.
  simplenotes.seenotes.*:
    description: Gives the permission to see the notes/warnings of all players.
    children:
      simplenotes.seenotes.self: true
      simplenotes.seenotes.others: true
  simplenotes.seenotes.self:
    description: Gives the permission to see your own notes/warnings
  simplenotes.seenotes.others:
    description: "Gives the permission to see other people's notes/warnings"
